### ISSUE TITLE
Status code "400"

### ISSUE THREAD

**Issue by CappiSteijns** [RakSrinaNa/ChannelPointsMiner#146]
### Description

Trying to set this up using a docker container on Unraid.

I've followed the steps with the help of #87 . But now I encounter the following error:

`[main] f.r.c.l.UnirestLogger {account_name=CappiSteijns} - Failed to request https://passport.twitch.tv/login got statusCode `400` and parsing error: Optional.empty
`

It also asks me to resolve an captcha in the browser? Not sure how to do this.

This happens after I enter the 2FA code. See the logs for more info. Any tips?

### Version / commit

0.0.8 | 1c96fba | main

### Relevant log output

```shell
Docker compose file:

version: "3.9"

services:
  miner:
    image: mrcraftcod/channel-points-miner:latest
    command: "--settings /mnt/user/appdata/config.json"
    volumes:
      - ./authentication:/mnt/user/appdata/authentication
      - ./streamers:/mnt/user/appdata/streamers
      - ./config.json:/mnt/user/appdata/config.json:ro

Config.json file:

{
  "accounts": [
    {
      "username": "CappiSteijns",
      "password": "XXXXXXXXXXXX",
      "use2FA": true,
      "loadFollows": true,
      "enabled": true,
      "defaultStreamerSettings": {
        "makePredictions": true,
        "followRaid": true,
        "participateCampaigns": true
      },
      "streamerConfigDirectories": [
        {
          "path": "streamers",
          "recursive": true
        }
      ],
      "discord": {
        "webhookUrl": "https://discord-webhook",
        "embeds": true
      },
      "reloadEvery": 15
    }
  ]
}

Log output:

root@CappiServer:/mnt/user/appdata/twitchpoints# docker run -it -v $(pwd)/authentication:/mnt/user/appdata/authentication -v $(pwd)/streamers:/mnt/user/appdata/streamers -v $(pwd)/config.json:/mnt/user/appdata/config.json mrcraftcod/channel-points-miner:latest --settings /mnt/user/appdata/config.json
14:58:28,142 INFO [main] f.r.c.Main {} - Starting everything up (0.0.8 | 1c96fba | main)
14:58:28,426 INFO [main] f.r.c.m.Miner {account_name=CappiSteijns} - Starting miner
Enter 2FA token:
XXXXXX
14:58:55,977 DEBUG [main] f.r.c.a.p.PassportApi {account_name=CappiSteijns} - Sending passport login request
14:58:56,185 TRACE [main] f.r.c.l.UnirestLogger {account_name=CappiSteijns} - Sending request to https://passport.twitch.tv/login
14:58:57,136 ERROR [main] f.r.c.l.UnirestLogger {account_name=CappiSteijns} - Failed to request https://passport.twitch.tv/login got statusCode `400` and parsing error: Optional.empty
Exception in thread "main" java.lang.IllegalStateException: A captcha solve is required, please log in through your browser and solve it
        at fr.raksrinana.channelpointsminer.miner.Miner.login(Miner.java:152)
        at fr.raksrinana.channelpointsminer.miner.Miner.start(Miner.java:120)
        at fr.raksrinana.channelpointsminer.Main.main(Main.java:46)
```

**Comment by RakSrinaNa** [comment]
If it asks for a captcha it means that Twitch is flagging your connection as being kinda suspicious and therefore asks you to solve a captcha. As It is right now I don't really have a workaround.

The most promising way would be to log in a browser outside of the docker container, extract the cookies and create the authentication file manually for the container. However I haven't described those steps yet.

I'll try to do so a bit later today.

**Comment by CappiSteijns** [comment]
> If it asks for a captcha it means that Twitch is flagging your connection as being kinda suspicious and therefore asks you to solve a captcha. As It is right now I don't really have a workaround.
> 
> The most promising way would be to log in a browser outside of the docker container, extract the cookies and create the authentication file manually for the container. However I haven't described those steps yet.
> 
> I'll try to do so a bit later today.

Thank you for the fast reply! I understand, I do have a cookie file since I used the miner from tkdalex. But I will wait for further instructions on how to do that! :)

**Comment by RakSrinaNa** [comment]
What I can say from now is that the format of the file is something like the following:

```json
{
    "accessToken": "xxxxxxxxxx",
    "cookies": [
        "header_name_1=value_1;Max-Age=0",
        "persistent=123456789%3A%3Axxxxxxxxx;Path=/;Domain=twitch.tv;Expires=Sun, 13-Nov-2022 16:07:04 GMT;HttpOnly;Secure"
    ],
    "username": "your_username"
}
```

In your case it'd be in the file `./authentication/cappisteijns.json`.

* AccessToken: I don't really know how you get it from the cookies. However when you login in the browser, you can look the network traffic, at some point it'll call `https://passport.twitch.tv`, you'll see the token in the response.
* Cookies: The cookies are stored here with the standard format, I left some examples. To be honest I don't think you need all cookies to be there, the only one needed is the `persistent` one (which should start with digits (your userId)).

I don't really know how familiar you are with dev tools in the browser but if you're at ease with it I guess the infos above are enough.
As you said you had the Tkd's version before you may be able to get those info from your previous cookies file. Though you'll have to get it in a readable format. If I remember well it uses pickle. So something like this may give you its content:

```py
import pickle

with open('filename', 'rb') as f:
    x = pickle.load(f)
   print(str(x))
```

**Comment by RakSrinaNa** [comment]
So for the format of the file you can refer yourself to the comment above.
To grab the values from your browser, first go on [twitch.tv](https://www.twitch.tv), log yourself in, and open the devtools (CTRL+SHIFT+I).

Then go to the `Application` tab and open the cookies for `https://www.twitch.tv`

![image](https://user-images.githubusercontent.com/1688389/154533535-c92bceeb-7b6e-4a70-877b-d69545b7f412.png)

You can find:
* AccessToken: this is the value of the `auth-token` cookie.
* Cookies: copy the persistent one.
* Username: this is the value of the `name` cookie.

You can copy the value of a cookie at the bottom of the panel after selecting the cookie you desire.

So this content file should be enough (AAAA value of `auth-token` cookie, BBBB value of `persistent` cookie, CCCC value of `name` cookie):
```json
{
    "accessToken": "AAAA",
    "cookies": [
        "persistent=BBBB;Path=/;Domain=twitch.tv;HttpOnly;Secure"
    ],
    "username": "CCCC"
}
```

**Comment by RakSrinaNa** [comment]
Your Auth file is not found. You'll have to indicate the location of the authentication folder.
So far you've mounted it but the app doesn't know where to find it.

And that makes me see that I actually forgot to mention it in the Readme 😂

Add to your config.json:
`"authenticationFolder": "/mnt/user/appdata/authentication"`.

**Comment by CappiSteijns** [comment]
> Your Auth file is not found. You'll have to indicate the location of the authentication folder. So far you've mounted it but the app doesn't know where to find it.
> 
> And that makes me see that I actually forgot to mention it in the Readme 😂
> 
> Add to your config.json: `"authenticationFolder": "/mnt/user/appdata/authentication"`.

That did the trick! 

I added the line to the config.json folder and it started working. 

I do have a lot of info in the logs since I cant seem to configure that. I've followed the steps from #87 but when I build the docker it will say:

`services.miner Additional property env is not allowed`

But I'm not going to worry about that anymore, it finally started to mine points :) 

Thanks you so much again for all the help!

**Comment by RakSrinaNa** [comment]
`Additional property env is not allowed` is docker indicating you that something is wrong with (probably) your compose file. I'd guess the indentation is not correct. You also have an example in the readme with the custom logger https://github.com/RakSrinaNa/ChannelPointsMiner#docker

**Comment by RakSrinaNa** [comment]
Or maybe I was sleeping when I wrote the doc 😆 what if you use `environment` instead of `env` ?

**Comment by CappiSteijns** [comment]
> 

Yeah, tried that but also couldn't get that to work.

At this point I just accepted i'm to incompetent to get it to work and to save myself the headaches I'll try again at a later point.

Thanks for all the help, will check back later!!
