### ISSUE TITLE
Body parse error with Twitch Guard

### ISSUE THREAD

**Issue by 15sawyer** [RakSrinaNa/ChannelPointsMiner#221]
### Description

The twitch guard system is currently broken:

> Failed to request https://passport.twitch.tv/login got statusCode `400` and parsing error: Optional[kong.unirest.core.UnirestParsingException: kong.unirest.core.UnirestException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "obscured_email" (class fr.raksrinana.channelpointsminer.miner.api.passport.data.LoginResponse), not marked as ignorable (7 known properties: "error_code", "error_description", "error", "access_token", "captcha_proof", "redirect_path", "sms_proof"])

Adding the following to LoginResponse.java solves the issue:
```
@JsonProperty("obscured_email")
@Nullable
private String obscuredEmail;
```

### Version / commit

b7518cd

**Comment by RakSrinaNa** [comment]
Fixed in 823a568a41a86d8aac1e4b4d783f0900ba0184ac, thanks !
