### ISSUE TITLE
automatically cheer 1 point to redeem 350 channel points

### ISSUE THREAD

**Issue by pilonull** [RakSrinaNa/ChannelPointsMiner#283]
### Description

thought it would be cool to have the bot automatically cheer 1 point/token/whatever it's called in order to claim the 350 bonus channel points per stream/day

**Comment by RakSrinaNa** [comment]
I'm not aware of that behavior. Do you have a like to the twitch help explaining it?

**Comment by pilonull** [comment]
> I'm not aware of that behavior. Do you have a like to the twitch help explaining it?
> 
> To me cheering is using bits. And this is using real money so probably won't be implementing this in the bot.

Ah, I guess it's the first cheer every 30 days, thought it was more frequently than that... 

https://help.twitch.tv/s/article/viewer-channel-point-guide?language=en_US#earn

and yea, I can see why you'd have that position, but 100 bits is $1.40 and 500 is $7.00 so cost per bit is like $0.015 

If you can only claim it once per streamer per month, 100 bits would last quite a long time for a decent amount of bonus points overall. 

Otherwise though, thanks for your time and awesome work!

**Comment by RakSrinaNa** [comment]
I understand that 1 bit isn't that much. But I still see it as risky. What if someday the bot is having issues and repeatedly send bits over and over until you're out of them. For the twitch it isn't an issue as you lose nothing from it, but with bits I don't really want to "take the risk" of wrongly manipulating bits. Even if it's just a batch of $5-$7.

Plus the cheering API is not publicly available. Would have to reverse engineer it like the rest of the program and so would make it quite unstable to anything that Twitch could change about it.
https://discuss.dev.twitch.tv/t/cheering-bits-api/28969/3

This also raises the question of how to make it monthly. Currently the program doesn't really have any state (except for analytics). It only reacts to events sent by twitch (someone goes online, a claim is available, ...).
The fact that this is a monthly thing, I think it's preferable to have it done manually or making a soft dedicated to cheering on a list of channels. Cheering one bit on like a dozen of channel each month shouldn't take that long.
