### ISSUE TITLE
No main config found

### ISSUE THREAD

**Issue by bitpushr** [RakSrinaNa/ChannelPointsMiner#87]
### Description

Java error message stating 'no main config found' despite config seemingly being placed in the correct spot. Example:

![image](https://user-images.githubusercontent.com/91350598/145104039-0c50a70b-a1a6-40fe-9f34-bfc938132bff.png)

Please advise on how to use config.json?

### Version / commit

0.0.4 / 98ae10a

### Relevant log output

```shell
PS C:\Users\HomeServer\.docker\Containers\Miner> docker-compose up
[+] Running 1/0
 - Container miner_TwitchMiner_1  Created                                                                          0.0s
Attaching to TwitchMiner_1
TwitchMiner_1  | 21:46:36,244 INFO [main] f.r.c.Main {} - Starting everything up (0.0.4 | 98ae10a | develop)
TwitchMiner_1  | Exception in thread "main" java.lang.IllegalStateException: No main config found
TwitchMiner_1  |        at fr.raksrinana.channelpointsminer.factory.ConfigurationFactory.getInstance(ConfigurationFactory.java:31)
TwitchMiner_1  |        at fr.raksrinana.channelpointsminer.Main.main(Main.java:42)
TwitchMiner_1  | Caused by: java.io.IOException: Is a directory
TwitchMiner_1  |        at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
TwitchMiner_1  |        at java.base/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:48)
TwitchMiner_1  |        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:330)
TwitchMiner_1  |        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:296)
TwitchMiner_1  |        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:273)
TwitchMiner_1  |        at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:229)
TwitchMiner_1  |        at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
TwitchMiner_1  |        at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107)
TwitchMiner_1  |        at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101)
TwitchMiner_1  |        at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.ensureLoaded(ByteSourceJsonBootstrapper.java:539)
TwitchMiner_1  |        at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.detectEncoding(ByteSourceJsonBootstrapper.java:133)
TwitchMiner_1  |        at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructParser(ByteSourceJsonBootstrapper.java:256)
TwitchMiner_1  |        at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1655)
TwitchMiner_1  |        at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1083)
TwitchMiner_1  |        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3675)
TwitchMiner_1  |        at fr.raksrinana.channelpointsminer.util.json.JacksonUtils.read(JacksonUtils.java:31)
TwitchMiner_1  |        at fr.raksrinana.channelpointsminer.factory.ConfigurationFactory.getInstance(ConfigurationFactory.java:28)
TwitchMiner_1  |        ... 1 more
TwitchMiner_1 exited with code 1
```

**Comment by RakSrinaNa** [comment]
Can you share the content of your `docker-compose.json` ?

You have a folder `.../.docker/Containers/Miner/config.json` with your config file inside, and my guess is that you're mounting it into your docker container instead of `.../.docker/Containers/Miner/config.json/config.json`.

**Comment by bitpushr** [comment]
I don't have a docker-compose.json, I've got a docker-compose.yml which is identical to the one in your readme. Should it not be a .yml?

**Comment by RakSrinaNa** [comment]
Yeah sorry .yml

**Comment by bitpushr** [comment]
> Yeah sorry .yml

version: "3.9"

services:
  miner:
    image: mrcraftcod/channel-points-miner:latest
    command: "--settings /usr/src/app/config.json"
    volumes:
      - ./authentication:/usr/src/app/authentication
      - ./streamers:/usr/src/app/streamers
      - ./config.json:/usr/src/app/config.json:ro

**Comment by RakSrinaNa** [comment]
`.../.docker/Containers/Miner/config.json` should be a file, not a folder. You probably started to compose stack once before the file was created so it made a folder by default. It has to be a file (the one you put inside the folder),

**Comment by bitpushr** [comment]
Gotcha. Have changed that, a step in the right direction :)

I'm now getting this:
![image](https://user-images.githubusercontent.com/91350598/145106458-100b219f-9cef-4a7d-abae-b5923583316f.png)
I'm not even getting a chance to enter the 2FA code.

**Comment by RakSrinaNa** [comment]
You have a 2FA token onto your account. However the container isn't started in an interactive mode so no inputs can be made.

You can run the container once without the docker compose in interactive mode to be able to enter the token:
```
docker run -it -v $(pwd)/authentication:/usr/src/app/authentication -v $(pwd)/streamers:/usr/src/app/streamers -v $(pwd)/config.json:/usr/src/app/config.json mrcraftcod/channel-points-miner:latest
```

I didn't try it, but you should be able to enter things when prompted. However when you'll close your terminal it'll close the app. So when logged, just stop the container (CTRL+C), authentication will be saved, and you can start the compose stack again.

**Comment by bitpushr** [comment]
Docker apparently says that's an 'invalid reference format' when running
docker run -it -v $(pwd)/authentication:/usr/src/app/authentication -v $(pwd)/streamers:/usr/src/app/streamers -v $(pwd)/config.json:/usr/src/app/config.json mrcraftcod/channel-points-miner:latest

Working on it...

**Comment by RakSrinaNa** [comment]
As you use powershell try replacing the `$(pwd)` with `${pwd}`

**Comment by bitpushr** [comment]
> 

Ah, right, that's done it. We're back to the previous 'no main config found' error message though. Just no reference to a folder this time.

**Comment by RakSrinaNa** [comment]
Alright, forgot to pass the argument at the end 😆 

`docker run -it -v ${pwd}/authentication:/usr/src/app/authentication -v ${pwd}/streamers:/usr/src/app/streamers -v ${pwd}/config.json:/usr/src/app/config.json mrcraftcod/channel-points-miner:latest --settings /usr/src/app/config.json`

**Comment by bitpushr** [comment]
> 

Woot. Looks like that's done it! :)
I _think_ it's working properly now? I got a whole dump of text here:
[Output.txt](https://github.com/RakSrinaNa/ChannelPointsMiner/files/7671737/Output.txt)

**Comment by RakSrinaNa** [comment]
You seem to be logged in, however you need to create a valid configuration:

* Your discord-webhook url is invalid. Put a valid one, or if you don't use it remove the whole `discord` block.
* The `streamerConfigDirectories` is invalid, in your case the path should be `/usr/src/app/streamers` instead of `streamers`

**Comment by RakSrinaNa** [comment]
You may want to provide a custom logger file to avoid having all the trace logs (it'll log a loooooot if you keep it this way)

**Comment by RakSrinaNa** [comment]
For the logs, you can create a file `logs.xml` next to your config.json, and put [this content](https://raw.githubusercontent.com/RakSrinaNa/ChannelPointsMiner/develop/src/examples/loggers/console_only.xml).

Then change your docker-compose.yml with:
```yml
version: "3.9"

services:
  miner:
    image: mrcraftcod/channel-points-miner:latest
    command: "--settings /usr/src/app/config.json"
    env:
      JDK_JAVA_OPTIONS: "-Dlog4j.configurationFile=/usr/src/app/log4j2.xml"
    volumes:
      - ./authentication:/usr/src/app/authentication
      - ./streamers:/usr/src/app/streamers
      - ./config.json:/usr/src/app/config.json:ro
      - ./logs.xml:/usr/src/app/log4j2.xml:ro
```

Restart your stack and it should "talk" a bit less 😆

**Comment by bitpushr** [comment]
> You seem to be logged in, however you need to create a valid configuration:
> 
> * Your discord-webhook url is invalid. Put a valid one, or if you don't use it remove the whole `discord` block.
> * The `streamerConfigDirectories` is invalid, in your case the path should be `/usr/src/app/streamers` instead of `streamers`

Think I've got it sorted now?
[Output.txt](https://github.com/RakSrinaNa/ChannelPointsMiner/files/7671880/Output.txt)

I'll look at setting up more finer logging once I know it's up and working :)

**Comment by RakSrinaNa** [comment]
`streamers/Quin69.json` seems to be empty, you need to define your streamer files with at least `{}` if you don't want to override default settings (the app used the defaults as it was invalid anyway). 

Other than that it seems ok, you can let it run for a bit and you should see info logs like `Points earned [+10 | WATCH | 10.50K]`.

**Comment by bitpushr** [comment]
> Other than that it seems ok, you can let it run for a bit and you should see info logs like `Points earned [+10 | WATCH | 10.50K]`.

Yep, just had it come through then :)
Cheers for the help; it's much appreciated. I'll look at setting up streamer-specifics and finer logging next/later on.
