### ISSUE TITLE
Any chance we could get an armhf Docker image?

### ISSUE THREAD

**Issue by StrangePeanut** [RakSrinaNa/ChannelPointsMiner#95]
### Description

Recently wanted to set up arm64 Docker but stuck to armhf since the former still wasn't fully supported. Think it would be nice to have armhf builds in the meantime. People with the original Pi would surely appreciate them also.

Actually been using your previous Twitch Channel Points Miner based images and wanted to switch to your new image today. Thanks for maintaining these.

**Comment by RakSrinaNa** [comment]
I'll look into it. As it is the [OpenJDK base image](https://hub.docker.com/layers/openjdk/library/openjdk/17-slim/images/sha256-f60a9fb1dc46e42d3a50f4f78acfd0404716afa18483bc068e58ac04fcca828b?context=explore) doesn't provide an armhf version. But it shouldn't be an issue switching to a JDK that provides it like bellsoft or something.

**Comment by RakSrinaNa** [comment]
When this build is done it should be available in the [develop](https://github.com/RakSrinaNa/ChannelPointsMiner/actions/runs/1563539843) tag. Feel free to reopen the issue if it doesn't work.

**Comment by StrangePeanut** [comment]
Cheers! Will give it a go and let you know if there are any issues.

**Comment by RakSrinaNa** [comment]
Well the build failed 😆

**Comment by RakSrinaNa** [comment]
Added 32e7ca1840bf7947128533dd0f08cbe09fc89191, it pushed a linux/arm but I think it's not enough and the linux/arm/v7 is needed?

**Comment by StrangePeanut** [comment]
Just gave it a try. Crashes with EXIT CODE 143 after showing the following line:

```shell
14:09:13,180 INFO [main] f.r.c.Main {} - Starting everything up (0.0.4 | 32e7ca1 | develop)
```

**Comment by StrangePeanut** [comment]
Yeah thought my Pi 3B+ was running out of memory also. Will try again after freeing up some tonight.
